//! Assembly patterns — linear and circular component arrays.

use serde::{Deserialize, Serialize};

use crate::error::{KernelError, KernelResult};
use crate::geometry::{Mat4, Vec3};
use crate::geometry::transform::{
    compose, from_array, rotation_axis_angle, to_array, translation,
};

use super::{Assembly, Component, Mate};

/// The kind of assembly pattern (linear or circular).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AssemblyPatternKind {
    Linear {
        direction: [f64; 3],
        spacing: f64,
    },
    Circular {
        axis_origin: [f64; 3],
        axis_direction: [f64; 3],
        angle_spacing: f64,
    },
}

/// An assembly pattern that replicates source components in a linear or circular array.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssemblyPattern {
    pub id: String,
    pub kind: AssemblyPatternKind,
    pub source_component_ids: Vec<String>,
    /// Total count including the original (must be >= 1).
    pub count: usize,
    /// IDs of components generated by this pattern (excluding sources).
    #[serde(default)]
    pub generated_component_ids: Vec<String>,
    /// IDs of mates generated by this pattern.
    #[serde(default)]
    pub generated_mate_ids: Vec<String>,
}

/// Compute the transform for instance `i` (1-based) of a pattern.
fn instance_transform(kind: &AssemblyPatternKind, i: usize) -> Mat4 {
    match kind {
        AssemblyPatternKind::Linear { direction, spacing } => {
            let offset = *spacing * i as f64;
            translation(
                direction[0] * offset,
                direction[1] * offset,
                direction[2] * offset,
            )
        }
        AssemblyPatternKind::Circular {
            axis_origin,
            axis_direction,
            angle_spacing,
        } => {
            let angle = *angle_spacing * i as f64;
            let axis = Vec3::new(axis_direction[0], axis_direction[1], axis_direction[2]);
            let origin = axis_origin;

            // Rotate around an arbitrary point:
            // T(origin) * R(angle) * T(-origin)
            let t_neg = translation(-origin[0], -origin[1], -origin[2]);
            let rot = rotation_axis_angle(&axis, angle);
            let t_pos = translation(origin[0], origin[1], origin[2]);
            compose(&t_pos, &compose(&rot, &t_neg))
        }
    }
}

/// Apply an assembly pattern, creating new components and replicating mates.
///
/// For each source component, creates `count - 1` new copies with computed transforms.
/// Replicates mates that reference source components to pattern instances.
/// Returns the IDs of all newly created components.
pub fn apply_assembly_pattern(
    assembly: &mut Assembly,
    pattern: &AssemblyPattern,
) -> KernelResult<Vec<String>> {
    if pattern.count < 1 {
        return Err(KernelError::InvalidParameter {
            param: "count".into(),
            value: pattern.count.to_string(),
        });
    }

    if pattern.source_component_ids.is_empty() {
        return Err(KernelError::InvalidParameter {
            param: "source_component_ids".into(),
            value: "empty".into(),
        });
    }

    // Validate source components exist
    for src_id in &pattern.source_component_ids {
        if !assembly.components.iter().any(|c| c.id == *src_id) {
            return Err(KernelError::NotFound(format!(
                "Source component '{}' not found",
                src_id
            )));
        }
    }

    let mut new_component_ids = Vec::new();
    let mut new_mate_ids = Vec::new();

    // Build a map from source component ID -> list of (instance_index, new_component_id)
    // for mate replication.
    let mut id_mapping: std::collections::HashMap<String, Vec<(usize, String)>> =
        std::collections::HashMap::new();

    // Create count-1 copies for each source component
    for src_id in &pattern.source_component_ids {
        let source = assembly
            .components
            .iter()
            .find(|c| c.id == *src_id)
            .unwrap()
            .clone();

        let source_transform = from_array(&source.transform);
        let mut instance_ids = Vec::new();

        for i in 1..pattern.count {
            let delta = instance_transform(&pattern.kind, i);
            let new_transform = compose(&delta, &source_transform);

            let new_id = format!(
                "{}-pattern-{}-{}",
                src_id, pattern.id, i
            );

            let mut new_comp = Component::new(
                new_id.clone(),
                source.part_id.clone(),
                format!("{} (Pattern {} #{})", source.name, pattern.id, i + 1),
            );
            new_comp.transform = to_array(&new_transform);
            new_comp.hidden = source.hidden;
            new_comp.grounded = source.grounded;
            new_comp.color_override = source.color_override;

            assembly.add_component(new_comp);
            new_component_ids.push(new_id.clone());
            instance_ids.push((i, new_id));
        }

        id_mapping.insert(src_id.clone(), instance_ids);
    }

    // Replicate mates: find mates where both components are source components
    let source_set: std::collections::HashSet<&String> =
        pattern.source_component_ids.iter().collect();

    let mates_to_replicate: Vec<Mate> = assembly
        .mates
        .iter()
        .filter(|m| {
            source_set.contains(&m.component_a) && source_set.contains(&m.component_b)
        })
        .cloned()
        .collect();

    for mate in &mates_to_replicate {
        let a_instances = id_mapping.get(&mate.component_a);
        let b_instances = id_mapping.get(&mate.component_b);

        if let (Some(a_list), Some(b_list)) = (a_instances, b_instances) {
            // For each instance index, replicate the mate
            for (a_idx, a_id) in a_list {
                // Find matching instance index in b
                if let Some((_, b_id)) = b_list.iter().find(|(bi, _)| bi == a_idx) {
                    let new_mate_id = format!(
                        "{}-pattern-{}-{}",
                        mate.id, pattern.id, a_idx
                    );
                    let mut new_mate = mate.clone();
                    new_mate.id = new_mate_id.clone();
                    new_mate.component_a = a_id.clone();
                    new_mate.component_b = b_id.clone();
                    assembly.mates.push(new_mate);
                    new_mate_ids.push(new_mate_id);
                }
            }
        }
    }

    // Also handle mates where only one side is a source component
    let mates_single_source: Vec<Mate> = assembly
        .mates
        .iter()
        .filter(|m| {
            source_set.contains(&m.component_a) ^ source_set.contains(&m.component_b)
        })
        .cloned()
        .collect();

    for mate in &mates_single_source {
        let (src_side, _other_id, is_a_source) = if source_set.contains(&mate.component_a) {
            (&mate.component_a, &mate.component_b, true)
        } else {
            (&mate.component_b, &mate.component_a, false)
        };

        if let Some(instances) = id_mapping.get(src_side) {
            for (idx, new_id) in instances {
                let new_mate_id = format!(
                    "{}-pattern-{}-{}",
                    mate.id, pattern.id, idx
                );
                let mut new_mate = mate.clone();
                new_mate.id = new_mate_id.clone();
                if is_a_source {
                    new_mate.component_a = new_id.clone();
                } else {
                    new_mate.component_b = new_id.clone();
                }
                assembly.mates.push(new_mate);
                new_mate_ids.push(new_mate_id);
            }
        }
    }

    // Store the pattern with generated IDs
    let mut stored_pattern = pattern.clone();
    stored_pattern.generated_component_ids = new_component_ids.clone();
    stored_pattern.generated_mate_ids = new_mate_ids;
    assembly.patterns.push(stored_pattern);

    Ok(new_component_ids)
}

/// Remove an assembly pattern and all its generated components and mates.
pub fn remove_assembly_pattern(assembly: &mut Assembly, pattern_id: &str) -> KernelResult<()> {
    let pattern = assembly
        .patterns
        .iter()
        .find(|p| p.id == pattern_id)
        .ok_or_else(|| KernelError::NotFound(format!("Pattern '{}' not found", pattern_id)))?
        .clone();

    // Remove generated components
    let gen_comp_set: std::collections::HashSet<&String> =
        pattern.generated_component_ids.iter().collect();
    assembly.components.retain(|c| !gen_comp_set.contains(&c.id));

    // Remove generated mates
    let gen_mate_set: std::collections::HashSet<&String> =
        pattern.generated_mate_ids.iter().collect();
    assembly.mates.retain(|m| !gen_mate_set.contains(&m.id));

    // Remove the pattern itself
    assembly.patterns.retain(|p| p.id != pattern_id);

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::assembly::{Assembly, Component, GeometryRef, Mate, MateKind, Part};
    use crate::feature_tree::{Feature, FeatureKind, FeatureParams, FeatureTree};
    use crate::geometry::surface::plane::Plane;
    use crate::geometry::{Pt2, Vec3};
    use crate::geometry::transform;
    use crate::operations::extrude::ExtrudeParams;
    use crate::sketch::constraint::{Constraint, ConstraintKind};
    use crate::sketch::entity::SketchEntity;
    use crate::sketch::Sketch;

    fn make_box_part(id: &str, name: &str) -> Part {
        let mut sketch = Sketch::new(Plane::xy(0.0));
        let p0 = sketch.add_entity(SketchEntity::Point { position: Pt2::new(0.0, 0.0) });
        let p1 = sketch.add_entity(SketchEntity::Point { position: Pt2::new(8.0, 0.5) });
        let p2 = sketch.add_entity(SketchEntity::Point { position: Pt2::new(8.0, 4.0) });
        let p3 = sketch.add_entity(SketchEntity::Point { position: Pt2::new(0.5, 4.0) });
        let bottom = sketch.add_entity(SketchEntity::Line { start: p0, end: p1 });
        let right = sketch.add_entity(SketchEntity::Line { start: p1, end: p2 });
        let top = sketch.add_entity(SketchEntity::Line { start: p2, end: p3 });
        let left = sketch.add_entity(SketchEntity::Line { start: p3, end: p0 });
        sketch.add_constraint(Constraint::new(ConstraintKind::Fixed, vec![p0]));
        sketch.add_constraint(Constraint::new(ConstraintKind::Horizontal, vec![bottom]));
        sketch.add_constraint(Constraint::new(ConstraintKind::Horizontal, vec![top]));
        sketch.add_constraint(Constraint::new(ConstraintKind::Vertical, vec![right]));
        sketch.add_constraint(Constraint::new(ConstraintKind::Vertical, vec![left]));
        sketch.add_constraint(Constraint::new(ConstraintKind::Distance { value: 10.0 }, vec![p0, p1]));
        sketch.add_constraint(Constraint::new(ConstraintKind::Distance { value: 5.0 }, vec![p1, p2]));

        let mut tree = FeatureTree::new();
        tree.push(Feature::new("s1".into(), "Sketch".into(), FeatureKind::Sketch, FeatureParams::Placeholder));
        tree.sketches.insert(0, sketch);
        tree.push(Feature::new("e1".into(), "Extrude".into(), FeatureKind::Extrude,
            FeatureParams::Extrude(ExtrudeParams::blind(Vec3::new(0.0, 0.0, 1.0), 7.0))));

        Part { id: id.into(), name: name.into(), tree, density: 1.0 }
    }

    #[test]
    fn linear_pattern_3_copies_along_x() {
        let mut assembly = Assembly::new();
        assembly.add_part(make_box_part("part1", "Box"));
        assembly.add_component(
            Component::new("comp1".into(), "part1".into(), "Box".into()),
        );

        let pattern = AssemblyPattern {
            id: "pat1".into(),
            kind: AssemblyPatternKind::Linear {
                direction: [1.0, 0.0, 0.0],
                spacing: 20.0,
            },
            source_component_ids: vec!["comp1".into()],
            count: 3,
            generated_component_ids: vec![],
            generated_mate_ids: vec![],
        };

        let new_ids = apply_assembly_pattern(&mut assembly, &pattern).unwrap();
        assert_eq!(new_ids.len(), 2, "Should create 2 new components (count=3 minus original)");
        assert_eq!(assembly.components.len(), 3);

        // Verify transforms: instance 1 at x=20, instance 2 at x=40
        let comp1 = assembly.components.iter().find(|c| c.id == new_ids[0]).unwrap();
        let t1 = transform::from_array(&comp1.transform);
        let pos1 = transform::get_translation(&t1);
        assert!((pos1.x - 20.0).abs() < 1e-9, "First copy at x=20, got x={}", pos1.x);
        assert!(pos1.y.abs() < 1e-9);
        assert!(pos1.z.abs() < 1e-9);

        let comp2 = assembly.components.iter().find(|c| c.id == new_ids[1]).unwrap();
        let t2 = transform::from_array(&comp2.transform);
        let pos2 = transform::get_translation(&t2);
        assert!((pos2.x - 40.0).abs() < 1e-9, "Second copy at x=40, got x={}", pos2.x);
    }

    #[test]
    fn circular_pattern_6_copies_around_z() {
        let mut assembly = Assembly::new();
        assembly.add_part(make_box_part("part1", "Box"));
        assembly.add_component(
            Component::new("comp1".into(), "part1".into(), "Box".into())
                .with_transform(transform::translation(10.0, 0.0, 0.0)),
        );

        let angle = std::f64::consts::TAU / 6.0; // 60 degrees
        let pattern = AssemblyPattern {
            id: "cpat1".into(),
            kind: AssemblyPatternKind::Circular {
                axis_origin: [0.0, 0.0, 0.0],
                axis_direction: [0.0, 0.0, 1.0],
                angle_spacing: angle,
            },
            source_component_ids: vec!["comp1".into()],
            count: 6,
            generated_component_ids: vec![],
            generated_mate_ids: vec![],
        };

        let new_ids = apply_assembly_pattern(&mut assembly, &pattern).unwrap();
        assert_eq!(new_ids.len(), 5, "Should create 5 new components (count=6 minus original)");
        assert_eq!(assembly.components.len(), 6);

        // Verify the translations of the generated components
        // Original is at (10, 0, 0). Instance i should be rotated by 60*i degrees.
        for (i, id) in new_ids.iter().enumerate() {
            let comp = assembly.components.iter().find(|c| c.id == *id).unwrap();
            let t = transform::from_array(&comp.transform);
            let pos = transform::get_translation(&t);
            let expected_angle = angle * (i + 1) as f64;
            let expected_x = 10.0 * expected_angle.cos();
            let expected_y = 10.0 * expected_angle.sin();
            assert!(
                (pos.x - expected_x).abs() < 1e-6,
                "Instance {} x: expected {}, got {}",
                i + 1,
                expected_x,
                pos.x
            );
            assert!(
                (pos.y - expected_y).abs() < 1e-6,
                "Instance {} y: expected {}, got {}",
                i + 1,
                expected_y,
                pos.y
            );
        }
    }

    #[test]
    fn mate_replication_coincident() {
        let mut assembly = Assembly::new();
        assembly.add_part(make_box_part("part1", "Box A"));
        assembly.add_part(make_box_part("part2", "Box B"));
        assembly.add_component(
            Component::new("compA".into(), "part1".into(), "A".into()),
        );
        assembly.add_component(
            Component::new("compB".into(), "part2".into(), "B".into())
                .with_transform(transform::translation(0.0, 5.0, 0.0)),
        );

        // Add a mate between the two source components
        assembly.mates.push(Mate {
            id: "mate1".into(),
            kind: MateKind::Coincident,
            component_a: "compA".into(),
            component_b: "compB".into(),
            geometry_ref_a: GeometryRef::Face(0),
            geometry_ref_b: GeometryRef::Face(1),
            suppressed: false,
        });

        let pattern = AssemblyPattern {
            id: "pat1".into(),
            kind: AssemblyPatternKind::Linear {
                direction: [1.0, 0.0, 0.0],
                spacing: 20.0,
            },
            source_component_ids: vec!["compA".into(), "compB".into()],
            count: 3,
            generated_component_ids: vec![],
            generated_mate_ids: vec![],
        };

        let new_ids = apply_assembly_pattern(&mut assembly, &pattern).unwrap();
        // 2 source components * 2 instances = 4 new components
        assert_eq!(new_ids.len(), 4);

        // Original mate + 2 replicated mates = 3 total
        assert_eq!(assembly.mates.len(), 3, "Should have 3 mates (1 original + 2 replicated)");

        // All replicated mates should be Coincident
        for mate in &assembly.mates {
            assert!(matches!(mate.kind, MateKind::Coincident));
        }

        // Verify replicated mates reference the correct new component IDs
        let replicated_mates: Vec<&Mate> = assembly
            .mates
            .iter()
            .filter(|m| m.id != "mate1")
            .collect();
        assert_eq!(replicated_mates.len(), 2);

        for m in &replicated_mates {
            // component_a should be a pattern instance of compA
            assert!(m.component_a.starts_with("compA-pattern-"));
            // component_b should be a pattern instance of compB
            assert!(m.component_b.starts_with("compB-pattern-"));
        }
    }

    #[test]
    fn pattern_deletion_removes_generated_components() {
        let mut assembly = Assembly::new();
        assembly.add_part(make_box_part("part1", "Box"));
        assembly.add_component(
            Component::new("comp1".into(), "part1".into(), "Box".into()),
        );

        let pattern = AssemblyPattern {
            id: "pat1".into(),
            kind: AssemblyPatternKind::Linear {
                direction: [1.0, 0.0, 0.0],
                spacing: 15.0,
            },
            source_component_ids: vec!["comp1".into()],
            count: 4,
            generated_component_ids: vec![],
            generated_mate_ids: vec![],
        };

        apply_assembly_pattern(&mut assembly, &pattern).unwrap();
        assert_eq!(assembly.components.len(), 4);
        assert_eq!(assembly.patterns.len(), 1);

        // Now remove the pattern
        remove_assembly_pattern(&mut assembly, "pat1").unwrap();
        assert_eq!(assembly.components.len(), 1, "Only original should remain");
        assert_eq!(assembly.components[0].id, "comp1");
        assert_eq!(assembly.patterns.len(), 0);
    }

    #[test]
    fn pattern_deletion_removes_generated_mates() {
        let mut assembly = Assembly::new();
        assembly.add_part(make_box_part("part1", "Box A"));
        assembly.add_part(make_box_part("part2", "Box B"));
        assembly.add_component(
            Component::new("compA".into(), "part1".into(), "A".into()),
        );
        assembly.add_component(
            Component::new("compB".into(), "part2".into(), "B".into()),
        );

        assembly.mates.push(Mate {
            id: "mate1".into(),
            kind: MateKind::Coincident,
            component_a: "compA".into(),
            component_b: "compB".into(),
            geometry_ref_a: GeometryRef::Face(0),
            geometry_ref_b: GeometryRef::Face(1),
            suppressed: false,
        });

        let pattern = AssemblyPattern {
            id: "pat1".into(),
            kind: AssemblyPatternKind::Linear {
                direction: [0.0, 1.0, 0.0],
                spacing: 10.0,
            },
            source_component_ids: vec!["compA".into(), "compB".into()],
            count: 3,
            generated_component_ids: vec![],
            generated_mate_ids: vec![],
        };

        apply_assembly_pattern(&mut assembly, &pattern).unwrap();
        assert_eq!(assembly.mates.len(), 3);
        assert_eq!(assembly.components.len(), 6);

        remove_assembly_pattern(&mut assembly, "pat1").unwrap();
        assert_eq!(assembly.mates.len(), 1, "Only original mate should remain");
        assert_eq!(assembly.mates[0].id, "mate1");
        assert_eq!(assembly.components.len(), 2, "Only original components should remain");
    }
}
